import { IBaseModel } from "./baseModel";
import { IsEmail,  IsNotEmpty, IsString, Length, Validate } from 'class-validator';
import { IsAutoGeneratedID, UniqueConstraint } from "../infra/repositories/repositoryDecorator";

export class Categoria {
    @Validate(UniqueConstraint)
    @IsString()
    @IsNotEmpty({message: 'O ID da categoria não deve ser vazio'})
    @IsAutoGeneratedID()
    id: string;
    @IsString()
    @IsNotEmpty({message: 'O campo descrição não deve ser vazio'})
    @Validate(UniqueConstraint)
    descricao: string;
}