import { IBaseModel } from "./baseModel";
import { IsEmail,  IsNotEmpty, IsString, Length, Validate, MinDate } from 'class-validator';
import { UniqueConstraint, IsAutoGeneratedID, CheckConstraintFK } from "../infra/repositories/repositoryDecorator";
import { Autor } from "./autor";

export class Livro implements IBaseModel {
    @Validate(UniqueConstraint)
    @IsString()
    @IsNotEmpty({message: 'O ID do livro não deve ser vazio'})
    @IsAutoGeneratedID()
    id: string;
    @IsString()
    @IsNotEmpty()
    nome: string;
    @IsString()
    @IsNotEmpty()
    @Length(500)
    resumo: string;
    @IsNotEmpty()
    @Length(100)
    sumario: string;
    preco: number;
    paginas: number;
    @Validate(UniqueConstraint)
    ISBN: string;
    @MinDate(new Date(), {message: 'Data de publicação inválida'})
    dataPublicacao: Date;
    @IsString()
    @IsNotEmpty()
    @CheckConstraintFK('Categoria', 'id')
    categoria: string;
    @CheckConstraintFK('Autor', 'id')
    autor: string;
}
